safe: true
lsi: false
future: true

title: Huon on the internet
markdown: kramdown

kramdown:
   footnote_nr: 0

highlighter: rouge

domain: huonw.github.io
url: https://huonw.github.io

permalink: /blog/:year/:month/:title/

twitter: huon_w
bluesky: huonw.bsky.social
exclude: ["vendor"]
blog_description: "Huon Wilson's writings"

defaults:
