safe: true
lsi: false
title: Huon on the internet
markdown: kramdown

kramdown:
   footnote_nr: 0

highlighter: rouge

domain: my-site.github.io
url: https://huonw.github.io

permalink: /blog/:year/:month/:title/

twitter: huon_w
exclude: ["vendor"]
blog_description: "Huon Wilson's writings"

defaults:
