safe: true
highlighter: pygments
lsi: false
title: huonw@github
markdown: kramdown

kramdown:
   footnote_nr: 0

breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

permalink: /blog/:year/:month/:title

twitter: huon_w
exclude: ["vendor"]
root: http://huonw.github.io
blog_description: "Huon Wilson's writings"

paginate: 10
paginate_path: "/blog/:num"

defaults:
